import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/component/Navbar";
import { Suspense } from "react";
import Footer from "./component/Footer";
import GlobalProvider from "./GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
 
  return (
    <html lang="en">
      <head>
        <title>shopify</title>
      </head>
      <body className={inter.className}>
        <GlobalProvider>
       <Navbar />
        <Suspense fallback={"Loading..."}>{children}</Suspense>
        <Footer/>
        </GlobalProvider>
      </body>
    </html>
  );
}
