import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/layout/Navbar";
import { Suspense } from "react";
import Footer from "./components/layout/Footer";
import AuthProvider from "@/providers/AuthProvider";
import GlobalProvider from "../providers/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>shopify</title>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <GlobalProvider>
            <Navbar />
            <Suspense fallback={"Loading..."}>{children}</Suspense>
            <Footer />
          </GlobalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
